### ISSUE TITLE
Error while trying to debug on device

### ISSUE THREAD

**Issue by Habaplap** [adjust/adobe_air_sdk#10]
Hi,
i get following Error Message when I try to debug my Application on an IOs Device.

![eroormessage](https://cloud.githubusercontent.com/assets/187615/6620569/c56e830e-c8d1-11e4-9b03-6057b2bdb5bc.jpg)

**Comment by nonelse** [comment]
I cannot replicate the issue. Can you try the example that is included here: https://github.com/adjust/adobe_air_sdk/tree/master/sample

If it's working, then it must be something more that exists in your app.
If not, it might be something in your system or device.

Either way, we can narrow down what might be the problem.

**Comment by uerceg** [comment]
@Habaplap Any progress with this issue?

**Comment by uerceg** [comment]
Please reopen this issue if you encounter this issue with our newest SDK version.
