### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by AlexeyMeshkov** [adjust/adobe_air_sdk#11]
We're using Adobe AIR version of our SDK and we want to use it to get install attribution data from the client. There is a callback that supposed to be used for it.  So the usage looks like this:

Adjust.appDidLaunch( ADJUST_APP_TOKEN, environment, logLevel, false );
Adjust.setResponseDelegate( adjustCallback );

But we're getting the response not every time. Sometimes it works, but sometimes not. I looked at your code on Github and it looks like you have a race condition. A callback can be set only after you call appDidLaunch, but that call initiates request to Adjust services and such request can finish before delegate is set.

**Comment by wellle** [comment]
@AlexeyMeshkov: You're right, that can happen. It will be fixed with the upcoming version 4 of the SDK.

**Comment by AlexeyMeshkov** [comment]
And what is estimated timeline for v4 to be released?

**Comment by uerceg** [comment]
@AlexeyMeshkov v4 is released: https://github.com/adjust/adobe_air_sdk/releases/tag/v4.0.0
