### ISSUE TITLE
Contex didnt create

### ISSUE THREAD

**Issue by mrcooper** [adjust/adobe_air_sdk#13]
Trying to debug Sample project

On Emulator with flag  Environment.SANDBOX it works

But on device with flag Environment.SANDBOX (either with Environment.PRODUCTION) we see error:
adjust error: cannot open ANE 'com.adjust.sdk' for this platform

**Comment by nonelse** [comment]
Thanks for the feedback.
It seems that the wrong adjust android jar was include in the `.ane`. The package of `v3.4.3` was replaced with the correct version.
