### ISSUE TITLE
Pass currency type/transaction ID through AIR SDK?

### ISSUE THREAD

**Issue by dfranzi** [adjust/adobe_air_sdk#14]
When attempting to track revenue events for Adjust through the Adobe AIR SDK, I can't seem to find anything about how to set the currency type for the tracked event. Additionally, is there a facility for providing the transaction ID to support revenue event deduplication through the AIR SDK?

**Comment by wellle** [comment]
@dfranzi: Currency support will be added with SDK version 4. Until that is released you are are advised to track all revenue in a single currency of your choice.

**Comment by dfranzi** [comment]
Thanks for the update. Is there an expected timeline for v4?

**Comment by wellle** [comment]
Not really.

**Comment by iangeisler** [comment]
Any update on v4? 

As it stands we can't use revenue data in Adjust and are having to look for alternatives.

**Comment by uerceg** [comment]
@iangeisler 

We are updating all our non native SDKs to v4 and starting from next week, we will start working on Adobe AIR SDK v4 update.

**Comment by iangeisler** [comment]
Any update on this?

**Comment by uerceg** [comment]
@iangeisler Few more weeks. Hopefully somewhere in 2nd half of August we're going to release update for Adobe AIR SDK.

**Comment by uerceg** [comment]
@iangeisler I just wanted to update you that during this week we'll be finishing Adobe AIR SDK v4.0.0 and will release it next week.

**Comment by uerceg** [comment]
@iangeisler And it's alive: https://github.com/adjust/adobe_air_sdk/releases/tag/v4.0.0

**Comment by iangeisler** [comment]
Thank you @uerceg.  Do we need to update the SDK in the game to have currency conversion work ?

**Comment by uerceg** [comment]
Yes, currency conversion is supported starting from v4.0.0. Upgrade to v4.0.0 brought some smaller API changes and migration guide when migrating from previous versions can be found in here: https://github.com/adjust/adobe_air_sdk/blob/master/doc/migrate.md

**Comment by nonelse** [comment]
Also @iangeisler, take note that the revenue now it's in units, not cents. So 51 cents of a dollar revenue would be tracked as `Adjust.trackRevenue(51,"abc123");`, it's now `config.setRevenue(0.51, "USD");`

**Comment by uerceg** [comment]
@iangeisler Since we spotted one bug in released ANE which needed to be fixed ASAP, please, re-download ANE 4.0.0 again and use that one.
