### ISSUE TITLE
Migration guide & app.xml

### ISSUE THREAD

**Issue by neuronix** [adjust/adobe_air_sdk#18]
Migration guide does not include important changes to the application.xml which can cause the app to crash on launch after following an adjust tracking link.

**Comment by uerceg** [comment]
@neuronix Thanks for the advice. We will consider `migrate.md` update with this info.

**Comment by uerceg** [comment]
@neuronix Were you referring to need to add this in `app.xml`:

```xml
<extensions>
    <!-- ... --->
    <extensionID>com.adjust.sdk</extensionID>
    <!-- ... --->
</extensions>
```

?

**Comment by neuronix** [comment]
@uerceg no, I was referring to the receiver class & package that changed in the update if I recall correctly.

**Comment by uerceg** [comment]
I think these were the things which we didn't cover in `migrate.md` and which have changed in 3.x.x -> 4.x.x upgrade:
https://github.com/adjust/adobe_air_sdk/blob/device_ids/doc/migrate.md#get-attribution-information
and
https://github.com/adjust/adobe_air_sdk/blob/device_ids/doc/migrate.md#broadcast-receiver

If you have anything else maybe you thing it is worth mentioning in here, feel free to suggest.

**Comment by uerceg** [comment]
@neuronix I will close this issue, since this is now officially merged into master branch (https://github.com/adjust/adobe_air_sdk/blob/master/doc/migrate.md).

Feel free to reopen the issue if you have any other suggestions.

Cheers
