### ISSUE TITLE
Add a .getID() function

### ISSUE THREAD

**Issue by neuronix** [adjust/adobe_air_sdk#19]
The whole thing about Adjust is trying to link the Adjust data to the app server's data, and there is a whole load of placeholder variables to try and match the data which is in fact totally overkill since we'd just need to match both sets of data with a single ID (whether it be ADID, IDFA, deviceID, whateverID)..

The whole process could be simplified with a simple and elegant .getId() function in the ANE. App server saves the id, and we match it with Adjust callbacks.

I tried explaining this slowly to the support team but I fear they missed the point completely.

**Comment by uerceg** [comment]
Hi @neuronix 

Which particular ID are you having in mind to get once calling that method?

**Comment by neuronix** [comment]
Hi @uerceg,

Well it doesn't really matter, as an app dev, we don't need to use the value for anything else than matching the data. This way, the adjust callback would have a single id placeholder. Ex: http://mybackend.com/adjust.php?adjust_id=<the .getId() value>&...<tracking data: refIds, subids etc.>

Another approach (which is widely used by third party advertisers, offerwalls etc.) would be to add a .setUserId(<my custom value>) method to the API so that devs can set their own user id value. This makes tracking very straight forward. Ex: http://mybackend.com/adjust.php?user_id=<my custom value>&...<tracking data: refIds, subids etc.>

If this is too much of a change to the API, you should at least add getters to the ANE so that devs are sure that both their backend and the adjust backend have the same values. Ideally there should be a getter for every single possible placeholder value. But the bare minimum should be: IDFA, Google ADID, Android deviceId etc.

Devs should have to include other third party ANEs to get these values.

**Comment by uerceg** [comment]
Hi @neuronix,

I see your point, we will discuss this internally what is doable and let you know as soon as we hit the decision. All of the changes we will perform need to be done on our native SDKs first and then exposed to Adobe AIR API.

I will keep you posted in this issue.

**Comment by neuronix** [comment]
Thanks @uerceg! Looking forward to the update :)

**Comment by neuronix** [comment]
Hi @uerceg, any news on this topic?

**Comment by uerceg** [comment]
Hi @neuronix 

We're preparing native SDK updates with following changes:
* For every event tracked, user will have possibility to define callback which is going to be triggered if event is tracked successfully and another which is going to be triggered if event tracking failed. In these callbacks, we will provide `adid` parameter as part of the response.
* iOS SDK will be expanded with method to get IDFA identifier.
* Android SDK will be expanded with method to get Google Play Services identifier.

Once added to native SDKs (hopefully this week, next one the latest) we'll start with non-native SDKs updates.

At this moment, these are the latest news.

**Comment by neuronix** [comment]
Thanks @uerceg ! :)

**Comment by uerceg** [comment]
@neuronix Sorry about delay due to a bit tight schedule, but here's an update for this issue. You can check https://github.com/adjust/adobe_air_sdk/pull/20 if you like.

With this version `4.1.0` we will add two new methods to `Adjust` interface - `getGoogleAdId` and `getIdfa` so that you can get these identifiers for now.

Event callbacks and access to `adid` parameter is something which is currently being implemented in native SDKs and is still not live. Once we add that functionality to native SDK, we'll eventually update Adobe AIR SDK as well.

I think we'll have this version officially released this week. Will keep you posted in here.

**Comment by neuronix** [comment]
@uerceg thanks for the good news! :)

**Comment by uerceg** [comment]
Hi @neuronix 

We have just released our latest `4.1.0` version (https://github.com/adjust/adobe_air_sdk/releases/tag/v4.1.0) where we enabled you to read advertising identifiers from the devices. For more info about changes, check: https://github.com/adjust/adobe_air_sdk/blob/master/CHANGELOG.md#version-410-23rd-march-2016

Hope it will serve your needs well. :)

Cheers

**Comment by neuronix** [comment]
Thanks @uerceg ! Hopefully this will make tracking more robust. Will test this soon!

**Comment by uerceg** [comment]
Great! Of course, let us know if it's working for you as expected and especially if you encounter any issues. :)

Cheers
