### ISSUE TITLE
Error #1006: value is not a function

### ISSUE THREAD

**Issue by tontonpiero** [adjust/adobe_air_sdk#24]
Hi,
I get this error just after starting the SDK on my iPad 2:
```
Error #1006: value is not a function
com.adjust.sdk::Adjust$/extensionResponseDelegate at /Users/AB/Dev/adobe_air_sdk/src/com/adjust/sdk/Adjust.as:185
```
This error disappears for a long time after that, and then happens again (I think it only happens when the Adjust session is starting).

I'm using the latest Adjust SDK and Air 24

**Comment by Obaied** [comment]
Hey @tontonpiero. Thanks for reporting the issue.

Can you paste how does your `EventSuccess` delegate looks line?

**Comment by tontonpiero** [comment]
Sure, here it is:
```
protected function init():void {
	var adjustConfig:AdjustConfig = new AdjustConfig(myAppToken, Environment.SANDBOX);
	adjustConfig.setLogLevel(LogLevel.VERBOSE);
	adjustConfig.setAttributionCallbackDelegate(handleAttribution);
	Adjust.start(adjustConfig);
}

protected function handleAttribution(attribution:AdjustAttribution):void {
	Log.debug("Tracker token = " + attribution.getTrackerToken());
	Log.debug("Tracker name = " + attribution.getTrackerName());
	Log.debug("Campaign = " + attribution.getCampaign());
	Log.debug("Network = " + attribution.getNetwork());
	Log.debug("Creative = " + attribution.getCreative());
	Log.debug("Adgroup = " + attribution.getAdGroup());
	Log.debug("Click label = " + attribution.getClickLabel());
}
```
I reverted to a previous version of Adjust SDK (4.1.0) and it works fine.

**Comment by Obaied** [comment]
Yep, got it. Thanks for reporting this. 
It is not a critical issue and will be fixed in upcoming release which is arriving soon. Thanks again for reporting it!

**Comment by Obaied** [comment]
@tontonpiero Thanks for your patience. This issue was fixed in the latest version. Please update and let us know if there is any further problems. I'll close the issue for now. Feel free to open it if necessary.
