### ISSUE TITLE
4.11 mentions Amazon AdId but nothing in API 

### ISSUE THREAD

**Issue by neuronix** [adjust/adobe_air_sdk#30]
Hi,

It seems that the getter for Amazon Fire Ad Id has been forgotten in the ANE's API. We have getIdfa(), getGoogleAdId() but no getAmazonAdId() or an equivalent.

Kind regards,

Nx

**Comment by uerceg** [comment]
Hi @neuronix 

The `CHANGELOG` entry about sending Amazon Advertising Identifier was actually referring to collecting it and sending it with the requests to our backend on Fire OS apps. We never actually added this method to our native Android SDK, thus there is none in Adobe AIR either. It was simply not requested so far by anyone.

If you would like to have it in SDK, we'll add it to our roadmap and probably add it to next native Android SDK minor release and then to Adobe AIR SDK as well once updated.

Cheers

**Comment by neuronix** [comment]
Hi @uerceg 

Thanks for the explanation. I am actually the dev who requested the getIdfa/getGoogleAdid methods since there were discrepencies between what we were collecting and what adjust was.

These methods allow us to work with the same values so it would be good to have the getAmazonAdId() method to continue with the same reasoning. Could you add that to next release?

Thanks,

Nx

**Comment by uerceg** [comment]
Sure, it is quite logical flow that we add this to our next minor release, having in mind that we already have these two methods for Google Ad Id and IDFA. :)

Will be added to next minor release for sure. At this moment, no ETA on this, but will update you in here on the progress.

Cheers.

**Comment by uerceg** [comment]
👋 @neuronix 

A bit of delay, but method finally added to the latest version: https://github.com/adjust/adobe_air_sdk/releases/tag/v4.12.0

Cheers.

**Comment by neuronix** [comment]
Hey! Just in time for the next build! Thanks @uerceg !
