### ISSUE TITLE
ANRs On Android

### ISSUE THREAD

**Issue by dcampano** [adjust/adobe_air_sdk#34]
Our application keeps getting ANRs that reference Adjust classes that are in a TimedWaiting state.  I'm attaching images of 2 of the ones that we have seen.  We are using the latest version of the ANE which looks like it uses the latest version of the Adjust Android sdk.

Do you have any insight on what is going on here?

![image](https://user-images.githubusercontent.com/21622/32690792-5b0f3d9c-c6ca-11e7-9183-1a35b24e5fd3.png)

![image](https://user-images.githubusercontent.com/21622/32690872-24429c4e-c6cc-11e7-9b7e-c3d8678a8913.png)

**Comment by dcampano** [comment]
Also, this line is using a method that Google says should only be used for debugging purposes.  As far as I can tell, all this even does is some extra logging.

https://github.com/adjust/android_sdk/blob/91107f1270922903c1835d6976b9466d96caf397/Adjust/adjust/src/main/java/com/adjust/sdk/ActivityHandler.java#L213

https://developer.android.com/reference/android/app/ActivityManager.html#getRunningAppProcesses()

**Comment by uerceg** [comment]
@dcampano

Thanks for reporting this to us.

We weren’t get this reported earlier. Is this something that you can reproduce? If yes, can you provide us with steps and also maybe description of device on which this happens?

Thanks in advance.

**Comment by Obaied** [comment]
@dcampano

An ANR can only happen when an application is doing too much work on the UI thread. From the thread dump above, you can see that a thread pool executor is being used, so none of the `Adjust-*` threads are running on the UI.

May I ask what lead you to believe that `Adjust-*` threads are the culprit?

**Comment by Obaied** [comment]
@dcampano 

Can you let us know if there's any progress on this?

**Comment by dcampano** [comment]
@Obaied I'm going to close this issue as I think it is more related to an Air issue in general and not caused by the Adjust plug in.  I apologize about the incorrect information on this and thanks for your response.
