### ISSUE TITLE
Amazon Install Referrer

### ISSUE THREAD

**Issue by rewb0rn** [adjust/adobe_air_sdk#38]
Hey there,

can you give us a quick note whether we should use the store intent or the install referrer API on Amazon. Or are neither of them supported outside Google Play?

Thanks in advance

**Comment by uerceg** [comment]
@rewb0rn 

Install referrer API is used by our SDK to communicate with Play Store app (made by Google) to get information about referrer information for app that got installed via Google Play Store. I don't think that this API works with Amazon store. As far as I know, there is no install referrer for Amazon like it exists in Android.

**Comment by uerceg** [comment]
Also, here's the reference from Amazon developer forum: https://forums.developer.amazon.com/questions/25601/how-to-track-install-referer.html

**Comment by rewb0rn** [comment]
Thanks for the info! Just to clarify, this means campaign tracking is currently not working with Adjust on Amazon devices and these installs would be seen as organic, correct? Regards

**Comment by uerceg** [comment]
No no, it works. You can check more about it in here: https://advertising.amazon.com/ad-specs/en/policy/mmp-measurement-urls

**Comment by rewb0rn** [comment]
Alright, thanks for the clarifications!
