### ISSUE TITLE
Amazon advertiser ID returns null

### ISSUE THREAD

**Issue by rewb0rn** [adjust/adobe_air_sdk#40]
Hello,

I am calling Adjust.getAmazonAdId() but in my test it always returns null. I was able to retrieve the advertiser Ids on iOS and Google Play without problems but can't make it work on the Amazon Appstore. 

I am testing on a Samsung Galaxy S7 with Amazon Appstore. Should the Amazon advertiser ID be available in this case or does it only exist on a Kindle Fire device?

Thanks in advance

**Comment by uerceg** [comment]
Hi @rewb0rn 

I don't think that presence of Amazon App Store on **Android** device causes the presence of Amazon Advertising Identifier. I think it exists only on the devices that are actually running Fire OS and according to the docs, it's available as of certain Fire OS 5.x versions. More info in here: https://developer.amazon.com/docs/fire-tablets/ft-advertising-id.html

Cheers

**Comment by rewb0rn** [comment]
Thanks I will use the google Ad Id in this case, which seems to be available.
