### ISSUE TITLE
Invalid architecture with latest Air 32.0.0.103 (iOS 12.1 update)

### ISSUE THREAD

**Issue by rewb0rn** [adjust/adobe_air_sdk#46]
Hello,

submitting our app to Apple through Application Loader with Adjust SDK 17.1 with the latest Air 32.0.0.103 beta (update for iOS SDK 12.1) I receive the following email from Apple:

_Dear Developer,_

_We identified one or more issues with a recent delivery for your app, "XXX". Please correct the following issues, then upload again._

_Invalid architectures - This app has invalid architecture, and may have been built with invalid build settings or incompatible tools. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider._

_Best regards,_

_The App Store Team_

Removing the Adjust ANE from the app fixes the problem, i.e. no other ANEs are producing this error. I also see this error when using Adjust 12.1 instead.

Can you have a look?

Thanks in advance

**Comment by uerceg** [comment]
Hi @rewb0rn

Thanks for the report. Hm. This is interesting. This latest version was built exactly for this reason - to please Apple's requirement to use latest Xcode for build process. 

Do you maybe have any additional info on which architecture in particular is invalid? Do you see same issue with 4.17.0?

**Comment by rewb0rn** [comment]
Hi,

thanks for your reply. Someone one the Adobe forums posted this, hope it helps:

_I read in another topic that if any ANE has a value of "-ios_version_min" lower than 8.0 in their platform.xml / platformoptions.xml file, you'll get that Invalid Architecture email from Apple since the newer 12.1 SDK or Xcode doesn't support a version that low.  I just downloaded the Adjust ANE and I see that it does in fact have -ios_version_min set to 6.0 in platformoptions.xml (none of the Distriqt or Milkman plugins that we use do), so that's likely the problem with their ANE._

**Comment by uerceg** [comment]
Interesting. This was doubt we had when releasing 4.17.1, but we did test with a client and it seemed that it was not needed, rather just to build the iOS binaries of the ANE with Xcode 10. 

If you can write me an email, I can provide you with the version of ANE which has minimal target iOS version changed to 8.0 and if it works for you, we will make it our 4.17.2 release.

**Comment by rewb0rn** [comment]
The issue only occurs with the latest Air SDK 32.0.0.103 that includes the update to iOS SDK 12.1. Previous versions of the Air SDK bundle 12.0 and do not produce the issue.

I have sent an email now, thanks for your help!

**Comment by uerceg** [comment]
Hey @rewb0rn,

Here's the RC 4.17.2 ANE which has **ios_version_min** set to **8.0**. In case it works for you, let us know and we can make it our new release.

(seems like GitHub doesn't allow `.ane` extension as attachment in comments, so I have literally just renamed it from .ane to .zip. Once downloaded, just rename it from .zip to .ane and should be fine)

[Adjust-4.17.2.zip](https://github.com/adjust/adobe_air_sdk/files/2888546/Adjust-4.17.2.zip)

**Comment by rewb0rn** [comment]
We have just submitted the app with Adjust 4.17.2 and we received the correct Apple email without complaints for an Invalid Architecture. Thanks for your support, this version does fix the problem.

**Comment by uerceg** [comment]
Awesome. Thanks for the update. We will release an official update later today.

**Comment by uerceg** [comment]
It's live: https://github.com/adjust/adobe_air_sdk/releases/tag/v4.17.2

Thank you one more time for the feedback and all the info.

Cheers! 🍺

**Comment by jeuxdaily** [comment]
hello
is that mean to change Milkman ane with this file Adjust-4.17.2.ane
thanks

**Comment by jeuxdaily** [comment]
I'm using Milkman plugin
thanks

**Comment by uerceg** [comment]
Hi @jeuxdaily.

Sorry, but I am not exactly sure what are you asking. I have just checked what Milkman is, seems like some platform where Adobe plugins are being distributed if I understood it well. Are you asking if Adjust ANE is available on Milkman platform? In case you are asking that, the answer is no, it is not.

**Comment by jeuxdaily** [comment]
thanks for your answer

but how can I solve this problem ..

I'm using adobe animate cc for mac

and if can I do some modification in xml file

thanks

**Comment by uerceg** [comment]
Hi @jeuxdaily 

I am not sure if Adjust SDK is something you need at all for this tool. Adjust SDK is used to enable users to make use of Adjust platform (more info in here: https://www.adjust.com/). It is used in case you are making mobile apps with Adobe AIR platform.

Adobe Animate CC seems like something totally unrelated to topic which Adjust SDK is made for, so not sure if you can do anything meaningful with it.

Cheers

**Comment by jeuxdaily** [comment]
hello
this my problem

Invalid architectures - This app has invalid architecture, and may have been built with invalid build settings or incompatible tools. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider.

this message was sent by apple developer after my app was successfully uploaded

**Comment by uerceg** [comment]
And if you remove Adjust ANE, then you're not seeing that error? Which Xcode version are you using?

**Comment by jeuxdaily** [comment]
hello
I don't work with Adjust ANE I work with milkman ANE

thanks for your answer

**Comment by uerceg** [comment]
Hi,

We don't really know how to help you with your issue. We would be able to help you if you were facing some issue with Adjust ANE, but we can't really provide support for ANE files we are not developing. 

Cheers

**Comment by jeuxdaily** [comment]
thanks foe you help

I solve my problem 

now it's working fine
thanks again

**Comment by jeuxdaily** [comment]
thanks you for your help
my problem is solved

**Comment by uerceg** [comment]
Awesome, thanks for the update! Cheers. 🍺

**Comment by rubel** [comment]
jeuxdaily
I am having the same problem here.
When we build our app with your admob extension and upload it using application load,
apple rejects that binary.
If we remove your extension and compile and then upload, apple takes that binary.

Can you please tell me how you fixed this problem?

**Comment by rubel** [comment]
> thanks foe you help
> 
> I solve my problem
> 
> now it's working fine
> thanks again

I am having the same problem here.
When we build our app with your admob extension and upload it using application load,
apple rejects that binary.
If we remove your extension and compile and then upload, apple takes that binary.

Can you please tell me how you fixed this problem?

**Comment by uerceg** [comment]
@rubel 

Are you seeing problem when adding Adjust ANE or AdMob ANE?

**Comment by rubel** [comment]
> @rubel
> 
> Are you seeing problem when adding Adjust ANE or AdMob ANE?

Thanks for the reply my friend
Milkman admob

**Comment by uerceg** [comment]
Like I already replied in comments above your question - we are not the ones who are developing that ANE and we can only help in case Adjust ANE is the one causing some issues.

**Comment by rewb0rn** [comment]
@rubel Milkman is no longer updating their extensions. Either change the minimum ios version for that ANE yourself by repackaging it, or use the updated ANE from another provider, like Distriqt.

**Comment by jeuxdaily** [comment]
> > thanks foe you help
> > I solve my problem
> > now it's working fine
> > thanks again
> 
> I am having the same problem here.
> When we build our app with your admob extension and upload it using application load,
> apple rejects that binary.
> If we remove your extension and compile and then upload, apple takes that binary.
> 
> Can you please tell me how you fixed this problem?

hello

have you this problem 
" Invalid architectures - This app has invalid architecture, and may have been built with invalid build settings or incompatible tools. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider. "

tell me

**Comment by amineunited** [comment]
> hello
> 
> have you this problem
> " Invalid architectures - This app has invalid architecture, and may have been built with invalid build settings or incompatible tools. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider. "
> 
> tell me

Hi friend i have the same problem with my ane admob milkman can you show me please the solution, thank you.

**Comment by dmkyrc** [comment]
have you this problem
 " Invalid architectures - This app has invalid architecture, and may have been built with invalid build settings or incompatible tools. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider. "

any solution?

**Comment by uerceg** [comment]
HI @dmkyrc 

Is it related with Adjust ANE? If yes, how do you know?

Cheers

**Comment by jeuxdaily** [comment]
> > thanks foe you help
> > I solve my problem
> > now it's working fine
> > thanks again
> 
> I am having the same problem here.
> When we build our app with your admob extension and upload it using application load,
> apple rejects that binary.
> If we remove your extension and compile and then upload, apple takes that binary.
> 
> Can you please tell me how you fixed this problem?

hi friend
have you solving your problem

**Comment by dmkyrc** [comment]
It was related with another ane not the problem for adjust. You should
check the other ane files. Mine was solved like that.

Thanks

**Comment by jeuxdaily** [comment]
> > hello
> > have you this problem
> > " Invalid architectures - This app has invalid architecture, and may have been built with invalid build settings or incompatible tools. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider. "
> > tell me
> 
> Hi friend i have the same problem with my ane admob milkman can you show me please the solution, thank you.

you open com.milkmangames.extensions.AdMob.ane

and go to folder

com.milkmangames.extensions.AdMob\META-INF\ANE\iPhone-ARM

open platform.xml

in line 8

<option>-ios_version_min 6</option>

change with this

<option>-ios_version_min 8.0</option>

good luck
