### ISSUE TITLE
install referrer ANE

### ISSUE THREAD

**Issue by rewb0rn** [adjust/adobe_air_sdk#54]
Hi,

when including the ANE `com.adjust.installref`, we are having a clash with another Adobe Native Extension that also contains the Google Install Referrer. When we include both `com.adjust.installref` and `com.android.installreferrer` by Distriqt (from here: https://github.com/distriqt/ANE-AndroidSupport), we see this error message:

```
dx tool failed:Error: Program type already present: com.android.installreferrer.BuildConfig
```

Can we just remove `com.adjust.installref` and everything would continue to work fine? Or is the file `AdjustInstallRef-1.0.0.ane` always required because it executes custom code for Adjust?

I checked the documentation but I only found [this link](https://github.com/adjust/android_sdk/blob/master/doc/english/misc/multiple-receivers.md) that explains how to handle the situation with broadcast receivers, which is the deprecated way.

Thanks in advance

**Comment by ugi** [comment]
Hi @rewb0rn,

In theory, that should be the case. Source of where API comes from should be irrelevant as long as it's there. You can also test this easily like this:

- Uninstall your app from test device.
- Set SDK to sandbox environment / log level to verbose.
- Install and start your app which launches Adjust SDK
- If you see in the logs that **sdk_click** type of package with parameter inside **source=install_referrer** is being sent in that launch sequence, that's an indicator that all works just fine from our SDK point of view.

Let us know if worked for you.

Cheers

**Comment by rewb0rn** [comment]
Where should I see this log? I have traced the jsonResponse in AS3 which gives this result:


```

jsonResponse = {"app_token":"XXX","adid":"XXX","timestamp":"2020-08-13T13:45:03.497Z+0000","message":"Install tracked","ask_in":2000}
Tracker token = XXX
Tracker name = Organic
Campaign = null
Network = Organic
Creative = null
Adgroup = null
Click label = null
```

However I don't see a **sdk_click** log, neither in AS3 nor logcat

**Comment by ugi** [comment]
Did you set SDK to sandbox mode and log level to verbose? You should be able to see native logs with `adb logcat -s Adjust`.

**Comment by rewb0rn** [comment]
Yes I set both, but apparently I used the filter in the Android Studio logcat wrong. With `adb logcat -s Adjust` the sdk_click and install referrer logs are showing up now.

This looks like it is working fine, thanks!

**Comment by ugi** [comment]
Yay, good news. In case anything else might be needed in here, feel free to comment/reopen.
