### ISSUE TITLE
I want to use `appTrackingAuthorizationStatus` method.

### ISSUE THREAD

**Issue by onsJP** [adjust/adobe_air_sdk#59]
Hi, 
I want to use `appTrackingAuthorizationStatus` method. 
Could you please support this?

https://github.com/adjust/ios_sdk/blob/master/Adjust/Adjust.h#L308

**Comment by uerceg** [comment]
Hi @onsJP, @paq

Yeah, this getter will become part of the next Adobe AIR SDK update. We will try to have it shipped by end of next week. Will keep you guys posted.

Cheers

**Comment by onsJP** [comment]
@uerceg 

Thank you for your reply.
I will wait for the next Adobe AIR SDK update.

**Comment by uerceg** [comment]
Hello guys.

And sorry for super belated reply from our end. I understand that it might not be a concern on your end anymore, but as of last week, we have upgraded Adobe AIR SDK to v5 and aligned it fully with features of our latest native SDKs. If this method is still something you need, the advice would be to [migrate from v4 to v5](https://github.com/adjust/adobe_air_sdk/blob/v5.0.0/MIGRATION.md) and then you'll have the ability to use [this getter](https://github.com/adjust/adobe_air_sdk?tab=readme-ov-file#att-status-getter).

Sorry one more time. I will close this ticket now, but in case you have follow up questions, feel free to comment / reopen.
