### ISSUE TITLE
using google play services ane and installreferrer ane from distriqt

### ISSUE THREAD

**Issue by Takeover-Interactive** [adjust/adobe_air_sdk#62]
I have followed the guide but keep getting these errors in my debug logs: 

11-12 13:33:02.805  8068  8499 E Adjust  : Failed to track session. (Certificate failed: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xd3c94e48: I/O error during system call, Connection reset by peer) Will retry later
11-12 13:33:02.805  8068  8499 E Adjust  : Failed with current url strategy, but it will retry with new
11-12 13:33:02.806  8068  8499 D Adjust  : Making request to url : https://app.adjust.net.in/session

there are more but would be too much to paste here. Only thing I did differently from the guide is use google play services ane and installreferrer ane from distriqt. would this cause issue? if so, how would it be resolved

**Comment by uerceg** [comment]
Hey @Takeover-Interactive,

Sorry for the amazingly belated reply on our end. To ask just in case - is this still an issue on your end in case you are still working on this project?

In theory, from what logs are saying, it seems like the error that has happened was the fact that the SDK wasn't able to send request to our backend. This can be happen if, for example, there's no internet connectivity, or maybe if you're behind the network that's using some VPN or firewall. Advice would be to retry this from device that's using mobile data, just to double check if it's still an issue on setup like that. I don't think that this error should have much to do with the fact that you're using these other ANEs.

Sorry one more time. I will close this ticket now, but in case you have questions / comments, feel free to comment / reopen.
